# Generated by Django 2.2.6 on 2019-10-14 13:34

import csv

from django.db import migrations

from django.contrib.gis.geos import Point

from ships.models import Ship, ShipLocation


def load_initial_data(apps, schema_editor):
    """ Load initial data. """
    with open("positions.csv") as csv_file:

        # Create test ships.
        ships = {
            9632179: Ship(name="Mathilde Maersk", imo=9632179),
            9247455: Ship(name="Australian Spirit​", imo=9247455),
            9595321: Ship(name="MSC Preziosa", imo=9595321),
        }
        for ship in ships.values():
            ship.save()

        # Create ships locations.
        reader = csv.reader(csv_file)
        for row in reader:
            ShipLocation(
                ship=ships[int(row[0])],
                timestamp=row[1],
                location=Point(float(row[3]), float(row[2])),
            ).save()


class Migration(migrations.Migration):

    dependencies = [("ships", "0001_initial")]

    operations = [migrations.RunPython(load_initial_data)]
